Controllers/BookController.cs
using Bookit.Data;
using Bookit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Bookit.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;
        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: Book
        public async Task<IActionResult> Index()
        {
            var categorylist = await _db.Categorys.ToListAsync();
            ViewData["categorylist"] = categorylist;
            return View(await _db.Books.ToListAsync());
        }
        // GET: Gallery
        [AllowAnonymous]
        [Route("book/gallery/{term?}")]
        public async Task<IActionResult> Gallery(string term = "")
        {
            dynamic model;
            if (string.IsNullOrEmpty(term))
            {
                model = await _db.Books.ToListAsync();
            }
            else
            {
                model = await _db.Books.Where(p => p.Name.Contains(term)).ToListAsync();
            }
            ViewData["term"] = term;
            return View(model);
        }
        // GET: Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categorylist = await _db.Categorys.ToListAsync();
            ViewData["categorylist"] = categorylist;
            return View();
        }
        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book model, IFormFile imageFile)
        {
            // Generate a unique file name
            string BookName = model.Name.Replace(" ", "_");
            string imageExtension = Path.GetExtension(imageFile.FileName);
            //string ImageName = BookName + imageExtension.Substring(imageExtension.LastIndexOf("."));                      
            // save in database
            Book bookModel = new Book()
            {
                Name = model.Name,
                CategoryId = model.CategoryId,
                Description = model.Description,
                Price = model.Price,
                Author = model.Author,
                Year = model.Year,
                Pages = model.Pages,
            };
            _db.Books.Add(bookModel);
            await _db.SaveChangesAsync();
            // update database
            int newBookId = bookModel.Id;
            // Define the path to save the image
            string ImageName = newBookId + "_" + BookName + imageExtension;
            var path = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Books\" + ImageName);
            // Save the image file
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await imageFile.CopyToAsync(stream);
            }
            bookModel.ImagePath = $"Books/{ImageName}";
            _db.Books.Update(bookModel);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await _db.Books.FirstOrDefaultAsync(m => m.Id == id);
            var categorylist = await _db.Categorys.ToListAsync();
            ViewData["categorylist"] = categorylist;
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book model, IFormFile imageFile)
        {
            // Generate a unique file name
            string BookName = model.Name.Replace(" ", "_");
            string imageExtension = Path.GetExtension(imageFile.FileName);
            // Define the path to save the image
            string ImageName = model.Id + "_" + BookName + imageExtension;
            var path = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Books\" + ImageName);
            // Save the image file
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await imageFile.CopyToAsync(stream);
            }
            model.ImagePath = $"Books/{ImageName}";
            // save in database
            _db.Books.Update(model);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: More
        [AllowAnonymous]
        public async Task<IActionResult> More(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await _db.Books.FirstOrDefaultAsync(m => m.Id == id);
            var categorylist = await _db.Categorys.ToListAsync();
            ViewData["categorylist"] = categorylist;
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        // GET: Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await _db.Books.FirstOrDefaultAsync(m => m.Id == id);
            var categorylist =await _db.Categorys.ToListAsync();
            ViewData["categorylist"] = categorylist;
            if (book == null || categorylist == null)
            {
                return NotFound();
            }
            var viewModel = new BookDetailsViewModel
            {
                Book = book,
                Categories = categorylist
            };
            return View(book);
        }
        // GET: Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await _db.Books.FirstOrDefaultAsync(m => m.Id == id);
            var categorylist =await _db.Categorys.ToListAsync();
            ViewData["categorylist"] = categorylist;
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        // POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Book model)
        {
            _db.Entry<Book>(model).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/CategoryController.cs
using Bookit.Data;
using Bookit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Bookit.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: Index
        public async Task<IActionResult> Index()
        {
            return View(await _db.Categorys.ToListAsync());
        }
        // GET: Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category model)
        {
            _db.Categorys.Add(model);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var model = await _db.Categorys.FindAsync(Id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category model)
        {
            _db.Entry<Category>(model).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: Details
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var model = await _db.Categorys.FindAsync(Id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        // GET: Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var model = await _db.Categorys.FindAsync(Id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        // POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Category model)
        {
            _db.Entry<Category>(model).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookit.Data;
using Bookit.Models;
using Microsoft.AspNetCore.Authorization;

namespace Bookit.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;

        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: Order
        public async Task<IActionResult> Index()
        {
            return View(await _db.Orders.ToListAsync());
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _db.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Order/Create
        [AllowAnonymous]
        public async Task<IActionResult> Create(int? bookId)
        {
            if (bookId == null)
            {
                return NotFound();
            }
            var book = await _db.Books.FindAsync(bookId);
            var model = new Order();
            model.Price = book.Price;
            model.BookId = book.Id;
            if (model == null)
            {
                return NotFound();
            }
            ViewData["book"] = book;
            return View(model);
        }

        // POST: Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create([Bind("Id,FullName,Address,PostalCode,PhoneNumber,BookId,Price,OrderState,TimeCreated")] Order order)
        {
            if (ModelState.IsValid)
            {
                order.TimeCreated = DateTime.Now;
                _db.Add(order);
                await _db.SaveChangesAsync();
                return RedirectToAction("Receipt", order);
            }
            return View(order);
        }

        // GET: Order/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _db.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Address,PostalCode,PhoneNumber,BookId,Price,OrderState,TimeCreated")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(order);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Order/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _db.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _db.Orders.FindAsync(id);
            _db.Orders.Remove(order);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _db.Orders.Any(e => e.Id == id);
        }
        public IActionResult Receipt(Order order)
        {
            return View(order);
        }
    }
}

Controllers/UserController.cs
using Bookit.Data;
using Bookit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Bookit.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: Index
        public async Task<IActionResult> Index()
        {
            return View(await _db.Users.ToListAsync());
        }
        // GET: Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User model)
        {
            _db.Users.Add(model);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var User = await _db.Users.FindAsync(id);
            if (User == null)
            {
                return NotFound();
            }
            return View(User);
        }
        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(User model)
        {
            _db.Entry<User>(model).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var User = await _db.Users.FindAsync(id);
            if (User == null)
            {
                return NotFound();
            }
            return View(User);
        }
        // GET: Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var User = await _db.Users.FindAsync(Id);
            if (User == null)
            {
                return NotFound();
            }
            return View(User);
        }
        // POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(User model)
        {
            _db.Entry<User>(model).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_BookItemPartial.cshtml
@model Bookit.Models.Book

<div class="col-sm-2">
    <img src="@Model.ImagePath" alt="@Model.Name" class="img-responsive" />
</div>
<div class="col-sm-10">
    <h4>@Model.Name (@Model.Year)</h4>
    <p>Author : @Model.Author</p>
    <p>Year : @Model.Year</p>
    <p>Pages : @Model.Pages</p>
    <p>Price : @Model.Price</p>
    <p>
        <a asp-action="More" asp-route-id="@Model.Id" asp-controller="Book" asp-area="" class="btn btn-primary">More...</a>
        <a asp-action="Create" asp-route-bookId="@Model.Id" asp-controller="Order" asp-area="" class="btn btn-success" style="width:200px">Order now</a>
    </p>
</div>

Views/Shared/_BookItemThumbPartial .cshtml
@model Bookit.Models.Book

<div class="col-sm-3">
    <img src="@Model.ImagePath" alt="@Model.Name" class="img-responsive" />
    <p>
        <a asp-action="More" asp-route-id="@Model.Id" asp-controller="Book" asp-area="" class="btn btn-primary">More...</a>
    </p>
</div>

Views/Shared/_BookItemThumbPartial.cshtml
@model Bookit.Models.Book

<div class="col-sm-3">
    <img src="@Model.ImagePath" alt="@Model.Name" class="img-responsive" style="width:100px;height:100px" />
    <p>
        <a asp-action="More" asp-route-id="@Model.Id" asp-controller="Book" asp-area="" class="btn btn-primary">More...</a>
    </p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookit</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Gallery">Gallery</a>
                        </li>
 @*                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Gallery</a>
                            </li>
                        } *@
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bookit - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>